Work cycles
pulibrary/drds-handbook-deprecated pull request #21
Opened 2019-11-08 22:03 UTC by hackmastera

can't merge until #16 is merged.

2019-11-11 14:48 UTC, jrgriffiniii commented on work_cycles.md
> +we plan to work during that cycle are placed in the "ready" column of the zenhub
Is the "icebox" column worth referencing in this section, or is this too specific to just Figgy? I would contend that the "inbox" to "ready" workflow is best left in the documentation for the Runner role.

2019-11-11 14:50 UTC, jrgriffiniii approved these changes

2019-11-12 14:30 UTC, hackmastera commented on work_cycles.md
> +we plan to work during that cycle are placed in the "ready" column of the zenhub
I was thinking that in the context of work cycles getting into the icebox would be a bit deep. Maybe we should have a ticket for explaining our board setup with more details? Interested in more thoughts here.

2019-11-12 14:34 UTC, hackmastera commented on work_cycles.md
> +cycle, with each sub-team. This means that we do not work on every application
should read "with each sub-team working on a different application or project"

2019-11-13 18:14 UTC, tpendragon requested changes
Looks good, I'd just like to see the "each sub-team working on a different application or project" get in, then we should merge.

2019-11-14 17:03 UTC, tpendragon approved these changes

2019-11-14 18:31 UTC, kelea99 reviewed
Looks good! A few comments below. take or leave as you see fit. Thank you!

2019-11-14 18:31 UTC, kelea99 commented on work_cycles.md
> +cycle, with each sub-team working on a different application or project. This means that we do not work on every application
Maybe reword this? I'm trying to keep your voice, promise. "This means that we work on a prioritized subset of applications for each sprint." or something like that?

2019-11-14 18:31 UTC, kelea99 commented on work_cycles.md
> +reach out to one another and to product owners and other stakeholders. While writing code often happens individually, software development is a highly collaborative activity. Knowledge about our appl
"and other teams". give examples? such as...? just a suggestion.

2019-11-14 18:31 UTC, kelea99 commented on work_cycles.md
> +Finally, we use Google drive record notes for meetings or produce design
....google drive _to_  record notes for meetings...

2019-11-14 18:31 UTC, kelea99 commented on work_cycles.md
> +Each of our projects has an assigned technical lead. This person will work most
re: tech leads-- perhaps cover this important point more clearly for the PO documentation- and (re-)affirmation what expectations are in regards to the lead and the PO (the communication info, for example, below), and refer back to who the tech leads are for each app in that same documentation? It was really helpful for me to see an actual list of the tech leads.  does this Make sense?

2019-11-14 20:33 UTC, hackartisan commented on work_cycles.md
> +Each of our projects has an assigned technical lead. This person will work most
The link to applications is in that other one. I've just add description to say that it includes the list of tech leads.

I'm not entirely sure I understand this comment. Are you asking for more info on the PO page or on the TL page? Or are you asking for something on this page?

2019-11-14 20:34 UTC, hackmastera commented
@kelea99 Otherwise I've made edits in response to your review. Thank you!

2019-11-16 12:46 UTC, kelea99 commented on work_cycles.md
> +Each of our projects has an assigned technical lead. This person will work most
Doh. Nope. you dont understand the comment, because it makes no sense! Sorry.  I Was reading one doc and didn't remember the link references from the other I read the evening before. Disregard.

2019-11-18 16:42 UTC, merged