Add product owner role description and links / details to applications
pulibrary/drds-handbook-deprecated pull request #22
Opened 2019-11-11 14:35 UTC by hackmastera

Do not merge before #16 and #21 as this branch is based on those.

closes #19
closes #20

2019-11-11 14:49 UTC, jrgriffiniii commented on applications.md
> +  * [Orangelight / Marc Liberation Zenhub board](https://app.zenhub.com/workspaces/orangelightmarcliberation-571691cab409d8d821b873be/board?repos=21954918)
👍 for the links to the Zenhub boards

2019-11-11 14:50 UTC, jrgriffiniii approved these changes

2019-11-11 14:52 UTC, jrgriffiniii commented on product_owners.md
> +We strive for each of our applications to have a product owner (PO). The product
It's a pedantic point, but there are going to be cases where we are required to have multiple product owners.

2019-11-11 15:00 UTC, hackmastera commented on product_owners.md
> +We strive for each of our applications to have a product owner (PO). The product
I wasn't sure I should get into all the details of why we prefer 1 and the exceptions, etc. If you have some wording you'd like to propose please go for it!

2019-11-13 18:16 UTC, tpendragon requested changes

2019-11-13 18:16 UTC, tpendragon commented on applications.md
>  ## Applications and their Technical Leads
Can we put known product owners here too? Or at least leave a space for them to be filled in.

2019-11-14 03:47 UTC, kelea99 reviewed
Hello, everyone! I think it looks great an have made only a couple of suggestions to the PO part here.

2019-11-14 03:47 UTC, kelea99 commented on product_owners.md
> +The exact practices of each product owner will very according to the application and the
type-o. vary vs. very

2019-11-14 03:47 UTC, kelea99 commented on product_owners.md
> +closely with us to guide development. In working with our team, product owners
wording here. perhaps saying the same thing a bit differently? up to you.  "We find that product owners who are familiar with our work cycles...etc....collaborate more effectively with our team." or something like that?

2019-11-14 03:47 UTC, kelea99 commented on product_owners.md
> +individuals themselves. Our hope is that product owners will be able to:
I would nix the "our hope is that".  I would keep the accountability equal between Product owners and DRDS, as you have below. you don't hope to, you will work to--and we should give you and the application that same dedication.  you could say "Generally, product owners will work to/be able to:"

2019-11-14 16:23 UTC, kelea99 commented on applications.md
>  ## Applications and their Technical Leads
I think that is a good idea

2019-11-14 17:49 UTC, hackmastera commented on applications.md
>  ## Applications and their Technical Leads
I can put a few. Maybe tech leads can fill them in once this is merged, too.

2019-11-14 17:53 UTC, hackmastera commented on product_owners.md
> +closely with us to guide development. In working with our team, product owners
I'll work on this thank you!

2019-11-14 17:54 UTC, hackmastera commented on product_owners.md
> +individuals themselves. Our hope is that product owners will be able to:
Will work on this also, thanks for pointing it out. I added the DRDS responsibilities later.

2019-11-14 18:16 UTC, hackmastera commented on applications.md
>  ## Applications and their Technical Leads
(I am thinking, in some cases there may be de facto product owners but I am not sure they are familiar with that term / role. We may want to touch base with people as we go along)

2019-11-14 18:30 UTC, hackmastera commented on applications.md
> +  * Product owners: [Faith](https://github.com/faithc) and [Amanda](https://library.princeton.edu/staff/amandapf)
I used a staff directory page here in lieu of a github account. does that seem okay?

2019-11-14 18:42 UTC, kelea99 commented on product_owners.md
> +closely with us to guide development. Documentation of our team's [work cycles](/work_cycles.md) and [technical lead role](/technical_leads.md) should give product owners useful context for this coll
sounds great!

2019-11-14 18:42 UTC, kelea99 commented on product_owners.md
> +* Work with the technical lead to prioritize and specify issues. It is helpful
I would say its more than helpful for the PO to have a GitHub account. Perhaps changing the wording a bit? such as: [while not required], Creating/Having a GitHub account will enable/empower the PO to be a more integrated part of the overall process with our team. or something like that?

2019-11-14 18:45 UTC, kelea99 commented on product_owners.md
> +* Work with the technical lead to prioritize and specify issues. It is helpful
maybe even nix the "while not required" part...

2019-11-14 18:50 UTC, hackmastera commented on product_owners.md
> +* Work with the technical lead to prioritize and specify issues. It is helpful
Okay I updated that; see what you think!

2019-11-14 18:55 UTC, kelea99 commented on product_owners.md
> +* Work with the technical lead to prioritize and specify issues. It is helpful
Looks good, @hackmastera !!

2019-11-14 18:57 UTC, kelea99 commented on applications.md
> +  * Product owners: [Faith](https://github.com/faithc) and [Amanda](https://library.princeton.edu/staff/amandapf)
Seems like the best idea. That way you can ensure you can add a link for everyone.

2019-11-14 20:04 UTC, escowles commented on applications.md
> +  * Product owners: [Faith](https://github.com/faithc) and [Amanda](https://library.princeton.edu/staff/amandapf)
You can change it to @apferrar

2019-11-14 20:26 UTC, hackmastera commented on applications.md
> +  * Product owners: [Faith](https://github.com/faithc) and [Amanda](https://library.princeton.edu/staff/amandapf)
done, thanks!

2019-11-18 16:43 UTC, tpendragon approved these changes

2019-11-18 16:44 UTC, merged