Migrate content from 'tools' google doc
pulibrary/drds-handbook-deprecated pull request #31
Opened 2020-03-26 15:49 UTC by hackmastera

Integrated the application list there into the one here.
Added 'tooling', 'overview', and 'administrative resources' pages.

closes #29

2020-03-26 15:57 UTC, christinach requested changes

2020-03-26 15:57 UTC, christinach commented on applications.md
> +  * Github repository: https://github.com/pulibrary/marc_liberation
We should update marc_liberation by having me as a tech lead.

2020-03-26 16:02 UTC, hackmastera commented on applications.md
> +  * Github repository: https://github.com/pulibrary/marc_liberation
good catch; that's done. Nikitas has 2 others; do we know what to put for those? or should we hold off for now?

2020-03-26 16:03 UTC, escowles commented on tooling.md
> +* [Lastpass](https://informationsecurity.princeton.edu/LastPass) for shared passwords
page to setup a lastpass account https://princeton.service-now.com/snap/kb_search.do?id=KB0011776 (FYI, if you link a personal account, it will start requiring 2FA for your personal account)

2020-03-26 16:03 UTC, escowles commented on tooling.md
> +* [Lastpass](https://informationsecurity.princeton.edu/LastPass) for shared passwords
Sorry, I see you've added the parent page with more info — that's probably better to link to!

2020-03-26 16:05 UTC, hackmastera commented on tooling.md
> +* [Lastpass](https://informationsecurity.princeton.edu/LastPass) for shared passwords
👍 yes I created the pr and then realized I needed to fill in that link. thanks!

2020-03-26 16:05 UTC, hackmastera commented on applications.md
> +  * Github repository: https://github.com/pulibrary/marc_liberation
(we decided to follow up later on OL)

2020-03-26 16:05 UTC, christinach approved these changes

2020-03-27 17:33 UTC, tpendragon approved these changes

2020-03-27 18:57 UTC, merged